import { AboutSlint, Button, VerticalBox, GroupBox, HorizontalBox } from "std-widgets.slint";

export component HelloWorld inherits Window {
  VerticalBox {
    HorizontalBox {
      GroupBox {
        title: "Controls";
        Text {
          text: "hello world";
          color: green;
        }
      }
      GroupBox {
        title: "Save States";
        Text {
          text: "hello world";
          color: green;
        }
      }
      GroupBox {
        title: "Log";
        Text {
          text: "hello world";
          color: green;
        }
      }
    }
    HorizontalBox {
      GroupBox {
        title: "Input Display";
        Text {
          text: "hello world";
          color: green;
        }
      }
      GroupBox {
        title: "Game Info";
        Text {
          text: "hello world";
          color: green;
        }
      }
    }
  }
}
