import {
  Palette,
  AboutSlint,
  Button,
  ComboBox,
  VerticalBox,
  GroupBox,
  HorizontalBox,
  TextEdit,
  StandardTableView,
  LineEdit,
} from "std-widgets.slint";

export component MainWindow inherits Window {
  preferred-width: 800px;
  preferred-height: 400px;

  // script menu
  callback open-script-dialog();
  in property<[string]> recent-scripts;
  in property<bool> valid-script-loaded;
  in property<string> script-name;
  in property<string> author;
  in property<int> frame-count;
  callback run-script();
  callback stop-script();
  callback pause-game();
  callback frame-advance();

  // logs
  in property<string> log;

  // input display
  pure callback build-image(length, length, int, ColorScheme) -> image;
  in property<int> input-sequence;

  // game information
  in property<string> stage-name;
  in property<int> scenario;
  in property<{ x: float, y: float, z: float }> position;

  VerticalBox {
    height: 100%;
    HorizontalBox {
      height: 50%;
      GroupBox {
        width: 33.3%;
        title: "Controls";
        VerticalBox {
          GridLayout {
            width: 100%;
            spacing: 0.5rem;
            Row {
              HorizontalBox {
                colspan: 2;
                padding: 0;
                // script name and open
                ComboBox {
                  height: 2.5rem;
                  preferred-width: 100%;
                  model: root.recent-scripts;
                  current-value: root.recent-scripts[0];
                }
                Button {
                  height: 2.5rem;
                  width: 6rem;
                  text: "Open";
                  clicked => open-script-dialog();
                }
              }
            }
            Row {
              Button {
                width: 50%;
                height: 2.5rem;
                text: "Run script";
                clicked => run-script();
              }
              Button {
                width: 50%;
                height: 2.5rem;
                text: "Stop script";
                clicked => stop-script();
              }
            }
            Row {
              Button {
                width: 50%;
                height: 2.5rem;
                text: "Pause game";
                clicked => pause-game();
              }
              Button {
                width: 50%;
                height: 2.5rem;
                text: "Frame advance";
                clicked => frame-advance();
              }
            }
            Row {
              GridLayout {
                colspan: 2;
                spacing: 0.5rem;
                Row {
                  Text {
                    text: "Script name";
                    vertical-alignment: center;
                  }
                  LineEdit {
                    preferred-width: 100%;
                    enabled: false;
                    read-only: true;
                    text: script-name;
                  }
                }
                Row {
                  Text {
                    text: "Author";
                    vertical-alignment: center;
                  }
                  LineEdit {
                    preferred-width: 100%;
                    enabled: false;
                    read-only: true;
                    text: author;
                  }
                }
                Row {
                  Text {
                    text: "Frame count";
                    vertical-alignment: center;
                  }
                  Text {
                    text: frame-count;
                    vertical-alignment: center;
                  }
                }
              }
            }
          }
          VerticalBox {
            HorizontalBox {

            }
          }
        }
      }
      GroupBox {
        title: "Savestates";
        Text {
          text: "not yet implemented";
        }
      }
      GroupBox {
        title: "Log";
        TextEdit {
          font-size: 14px;
          text: root.log;
        }
      }
    }
    lower := HorizontalBox {
      height: 50%;
      input-display-group := GroupBox {
        width: 50%;
        title: "Input Display";
        Rectangle {
          display := Image {
            x: 0;
            y: 0;
            source: build-image(parent.width, parent.height, input-sequence, Palette.color-scheme);
          }
        }
      }
      GroupBox {
        title: "Game Info";
        StandardTableView {
          rows: [
            [{ text: "Stage Name" }, { text: "\{stage-name} (scenario: \{scenario})" }],
            [{ text: "Player Position" }, { text: "(\{position.x}, \{position.y}, \{position.z})" }],
          ];
        }
      }
    }
  }
}
